import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'whybuilder_api.settings')
django.setup()

from properties.models import Property
from users.models import User

# Get first landlord user or create one
user = User.objects.filter(account_type='landlord').first()
if not user:
    user = User.objects.create_user(
        username='landlord1',
        email='landlord@whybuilder.com',
        password='WhyBuilder2026',
        first_name='John',
        last_name='Landlord'
    )
    # Set account_type separately if your model has it
    user.account_type = 'landlord'
    user.save()

# Clear existing properties
Property.objects.all().delete()

# Define complete property data with renamed images
properties_data = [
    # === KAREN PROPERTIES ===
    {
        "title": "Spacious Karen Family Home",
        "description": "Beautiful 4-bedroom family home in peaceful Karen. Large garden, mature trees, and stunning views.",
        "address": "20 Karen Road",
        "area": "Karen",
        "city": "Nairobi",
        "price_per_month": 85000,
        "bedrooms": 4,
        "bathrooms": 3,
        "size_sqft": 3200,
        "property_type": "House",
        "safety_score": 94,
        "noise_level": "quiet",
        "commute_rating": 82,
        "lifestyle_tags": ["Quiet living", "Family living"],
        "area_insight": "Karen offers a serene environment with plenty of green spaces.",
        "listing_status": "verified",
        "has_parking": True,
        "has_security": True,
        "has_gym": False,
        "has_pool": False,
        "has_ac": True,
        "pet_friendly": True,
        "image_url": "/images/properties/karen-family-peaceful-01.jpg"
    },
    {
        "title": "Modern Karen Townhouse",
        "description": "Contemporary 3-bedroom townhouse in a secure gated community with pool and gym access.",
        "address": "45 Karen Plains",
        "area": "Karen",
        "city": "Nairobi",
        "price_per_month": 95000,
        "bedrooms": 3,
        "bathrooms": 2.5,
        "size_sqft": 2800,
        "property_type": "Townhouse",
        "safety_score": 92,
        "noise_level": "quiet",
        "commute_rating": 80,
        "lifestyle_tags": ["Quiet living", "Family living"],
        "area_insight": "A secure, family-friendly neighborhood with excellent amenities.",
        "listing_status": "verified",
        "has_parking": True,
        "has_security": True,
        "has_gym": True,
        "has_pool": True,
        "has_ac": True,
        "pet_friendly": False,
        "image_url": "/images/properties/karen-family-peaceful-02.jpg"
    },
    {
        "title": "Green Karen Eco-Home",
        "description": "Sustainable 3-bedroom home with solar panels and rainwater harvesting.",
        "address": "12 Green Valley, Karen",
        "area": "Karen",
        "city": "Nairobi",
        "price_per_month": 78000,
        "bedrooms": 3,
        "bathrooms": 2,
        "size_sqft": 2400,
        "property_type": "House",
        "safety_score": 93,
        "noise_level": "quiet",
        "commute_rating": 76,
        "lifestyle_tags": ["Quiet living", "Work-friendly zones"],
        "area_insight": "A green, sustainable community with a focus on environmental living.",
        "listing_status": "verified",
        "has_parking": True,
        "has_security": True,
        "has_gym": False,
        "has_pool": False,
        "has_ac": True,
        "pet_friendly": True,
        "image_url": "/images/properties/karen-green-01.jpg"
    },
    {
        "title": "Spacious Karen Bungalow",
        "description": "Charming 5-bedroom bungalow on a large plot with mature gardens.",
        "address": "78 Karen Gardens",
        "area": "Karen",
        "city": "Nairobi",
        "price_per_month": 120000,
        "bedrooms": 5,
        "bathrooms": 4,
        "size_sqft": 4000,
        "property_type": "House",
        "safety_score": 95,
        "noise_level": "quiet",
        "commute_rating": 78,
        "lifestyle_tags": ["Quiet living", "Family living"],
        "area_insight": "One of Nairobi's most prestigious neighborhoods with large plots.",
        "listing_status": "verified",
        "has_parking": True,
        "has_security": True,
        "has_gym": False,
        "has_pool": False,
        "has_ac": True,
        "pet_friendly": True,
        "image_url": "/images/properties/karen-spacious-01.jpg"
    },

    # === LAVINGTON PROPERTIES ===
    {
        "title": "Executive Lavington Villa",
        "description": "Luxury 4-bedroom villa with high-end finishes, private garden, and 24/7 security.",
        "address": "10 Lavington Drive",
        "area": "Lavington",
        "city": "Nairobi",
        "price_per_month": 110000,
        "bedrooms": 4,
        "bathrooms": 3.5,
        "size_sqft": 3500,
        "property_type": "Villa",
        "safety_score": 91,
        "noise_level": "quiet",
        "commute_rating": 87,
        "lifestyle_tags": ["Work-friendly zones", "Quiet living"],
        "area_insight": "Lavington offers an executive lifestyle with excellent schools.",
        "listing_status": "verified",
        "has_parking": True,
        "has_security": True,
        "has_gym": True,
        "has_pool": True,
        "has_ac": True,
        "pet_friendly": False,
        "image_url": "/images/properties/lavington-luxury-01.jpg"
    },
    {
        "title": "Modern Lavington Apartment",
        "description": "Stylish 2-bedroom apartment with rooftop terrace, gym, and secure parking.",
        "address": "5 Lavington Towers",
        "area": "Lavington",
        "city": "Nairobi",
        "price_per_month": 65000,
        "bedrooms": 2,
        "bathrooms": 2,
        "size_sqft": 1500,
        "property_type": "Apartment",
        "safety_score": 89,
        "noise_level": "moderate",
        "commute_rating": 85,
        "lifestyle_tags": ["Work-friendly zones"],
        "area_insight": "A modern, secure apartment complex ideal for young professionals.",
        "listing_status": "verified",
        "has_parking": True,
        "has_security": True,
        "has_gym": True,
        "has_pool": False,
        "has_ac": True,
        "pet_friendly": False,
        "image_url": "/images/properties/lavington-established-01.jpg"
    },
    {
        "title": "Peaceful Lavington Bungalow",
        "description": "Charming 3-bedroom bungalow with beautiful garden. Close to international schools.",
        "address": "32 Lavington Lane",
        "area": "Lavington",
        "city": "Nairobi",
        "price_per_month": 85000,
        "bedrooms": 3,
        "bathrooms": 2,
        "size_sqft": 2200,
        "property_type": "House",
        "safety_score": 92,
        "noise_level": "quiet",
        "commute_rating": 83,
        "lifestyle_tags": ["Quiet living", "Work-friendly zones"],
        "area_insight": "A peaceful residential area with a strong community feel.",
        "listing_status": "verified",
        "has_parking": True,
        "has_security": True,
        "has_gym": False,
        "has_pool": False,
        "has_ac": True,
        "pet_friendly": True,
        "image_url": "/images/properties/lavington-quiet-01.jpg"
    },
    {
        "title": "Elegant Lavington Home",
        "description": "Beautiful 4-bedroom home with high ceilings, mature garden, and swimming pool.",
        "address": "15 Lavington Green",
        "area": "Lavington",
        "city": "Nairobi",
        "price_per_month": 95000,
        "bedrooms": 4,
        "bathrooms": 3,
        "size_sqft": 3000,
        "property_type": "House",
        "safety_score": 90,
        "noise_level": "quiet",
        "commute_rating": 84,
        "lifestyle_tags": ["Family living", "Quiet living"],
        "area_insight": "An elegant, established neighborhood with tree-lined streets.",
        "listing_status": "verified",
        "has_parking": True,
        "has_security": True,
        "has_gym": False,
        "has_pool": True,
        "has_ac": True,
        "pet_friendly": False,
        "image_url": "/images/properties/lavington-luxury-02.jpg"
    },

    # === WESTLANDS PROPERTIES ===
    {
        "title": "Modern Westlands Penthouse",
        "description": "Spectacular 3-bedroom penthouse with panoramic city views and rooftop terrace.",
        "address": "1 Westlands Heights",
        "area": "Westlands",
        "city": "Nairobi",
        "price_per_month": 90000,
        "bedrooms": 3,
        "bathrooms": 2,
        "size_sqft": 2200,
        "property_type": "Apartment",
        "safety_score": 88,
        "noise_level": "lively",
        "commute_rating": 92,
        "lifestyle_tags": ["Social areas", "Urban living"],
        "area_insight": "Westlands is the heart of Nairobi's business and entertainment district.",
        "listing_status": "verified",
        "has_parking": True,
        "has_security": True,
        "has_gym": True,
        "has_pool": False,
        "has_ac": True,
        "pet_friendly": False,
        "image_url": "/images/properties/westlands-urban-01.jpg"
    },
    {
        "title": "Connected Westlands Apartment",
        "description": "Convenient 2-bedroom apartment with easy access to CBD, malls, and restaurants.",
        "address": "45 Westlands Road",
        "area": "Westlands",
        "city": "Nairobi",
        "price_per_month": 55000,
        "bedrooms": 2,
        "bathrooms": 1.5,
        "size_sqft": 1200,
        "property_type": "Apartment",
        "safety_score": 86,
        "noise_level": "lively",
        "commute_rating": 93,
        "lifestyle_tags": ["Social areas", "Urban living"],
        "area_insight": "A vibrant neighborhood with everything within walking distance.",
        "listing_status": "verified",
        "has_parking": True,
        "has_security": True,
        "has_gym": False,
        "has_pool": False,
        "has_ac": True,
        "pet_friendly": False,
        "image_url": "/images/properties/westlands-vibrant-01.jpg"
    },
    {
        "title": "Vibrant Westlands Studio",
        "description": "Stylish studio apartment walking distance to malls, restaurants, and nightlife.",
        "address": "22 Westlands Park",
        "area": "Westlands",
        "city": "Nairobi",
        "price_per_month": 35000,
        "bedrooms": 0,
        "bathrooms": 1,
        "size_sqft": 500,
        "property_type": "Studio",
        "safety_score": 85,
        "noise_level": "lively",
        "commute_rating": 94,
        "lifestyle_tags": ["Social areas", "Urban living"],
        "area_insight": "Perfect for singles and young professionals in the heart of the action.",
        "listing_status": "verified",
        "has_parking": True,
        "has_security": True,
        "has_gym": False,
        "has_pool": False,
        "has_ac": True,
        "pet_friendly": False,
        "image_url": "/images/properties/westlands-modern-01.jpg"
    },
    {
        "title": "Urban Westlands 3-Bedroom",
        "description": "Spacious 3-bedroom apartment with gym, pool, and rooftop garden.",
        "address": "78 Westlands Estate",
        "area": "Westlands",
        "city": "Nairobi",
        "price_per_month": 75000,
        "bedrooms": 3,
        "bathrooms": 2,
        "size_sqft": 1800,
        "property_type": "Apartment",
        "safety_score": 87,
        "noise_level": "moderate",
        "commute_rating": 91,
        "lifestyle_tags": ["Social areas", "Urban living"],
        "area_insight": "A modern urban living space with excellent amenities.",
        "listing_status": "verified",
        "has_parking": True,
        "has_security": True,
        "has_gym": True,
        "has_pool": True,
        "has_ac": True,
        "pet_friendly": False,
        "image_url": "/images/properties/westlands-vibrant-02.jpg"
    },
]

print(f"Creating {len(properties_data)} properties...")

for data in properties_data:
    property = Property.objects.create(
        landlord=user,
        **data
    )
    print(f"✓ Created: {property.title}")

print(f"\n✅ Successfully created {len(properties_data)} properties!")
