# Generated by Django 6.0.6 on 2026-06-28 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(default='Nairobi', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_accuracy', models.CharField(choices=[('gps', 'GPS exact'), ('address', 'Address based'), ('manual', 'Manually placed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('price_per_month', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('size_sqft', models.IntegerField(blank=True, null=True)),
                ('property_type', models.CharField(max_length=50)),
                ('safety_score', models.IntegerField(help_text='0-100')),
                ('noise_level', models.CharField(choices=[('quiet', 'Quiet'), ('moderate', 'Moderate'), ('lively', 'Lively')], default='moderate', max_length=20)),
                ('commute_rating', models.IntegerField(help_text='0-100')),
                ('lifestyle_tags', models.JSONField(default=list)),
                ('area_insight', models.TextField(blank=True)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('listing_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
